CREATE TABLE everest_schools (
    school_id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    school_name TEXT NOT NULL,
    school_type TEXT NOT NULL,
    school_size INTEGER,
    public_or_private TEXT,
    curriculum TEXT,
    location TEXT,
    notable_facts TEXT,
    school_website TEXT,
    apartment_provided BOOLEAN,
    housing_assistance TEXT,
    size_of_housing TEXT,
    -- shared_room BOOLEAN,
    -- private_room BOOLEAN,
    shared_or_private_living_space TEXT,
    housing_notes TEXT,
    housing_on_or_off TEXT,
    time_to_get_to_class TEXT,
    distance_to_public_trans TEXT,
    school_charge_rent BOOLEAN,
    school_rent_notes TEXT,
    school_charge_utils BOOLEAN,
    school_utils_notes TEXT,
    furnished BOOLEAN,
    furnished_notes TEXT,
    appliances_included TEXT,
    internet TEXT,
    computer_included TEXT,
    school_provide_health_insurance BOOLEAN,
    provided_insurance_notes TEXT,
    medical_expeneses_paid TEXT,
    disability_insurance BOOLEAN,
    other_insurance BOOLEAN,
    assistance_obtaining_work_visa BOOLEAN,
    school_pay_work_visa TEXT,
    school_reimburse_costs_for_obtaining_visa_in_us BOOLEAN,
    assistance_opening_chinese_bank_account BOOLEAN,
    assistance_shopping_and_settling_in BOOLEAN,
    organized_trips_for_teachers BOOLEAN,
    other_western_teachers_at_school INTEGER,
    western_amenities_available_near_school_town TEXT,
    school_approved BOOLEAN NOT NULL DEFAULT false
);
